@host=http://insurance.selv.local:81
###
POST /v1/credentials
###
GET /v1/credentials/{credential_id}
###
POST /v1/offers
###
POST /v1/authorization_requests
Content-Type: application/json
{
    "nonce": "0d520cbe176ab9e1f7888c70888020d84a69672a4baabd3ce1c6aaad8f6420c0"
}
###
GET /v1/authorization_requests/06adfc99a128b078726c9cca383df3883db1e8dbd0270518bd4af7eb5a8e9191
###
POST /redirect
Content-Type: application/x-www-form-urlencoded

id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRpZDppb3RhOnJtczoweDI5YTY2YWE0MjkwMmQzYmE4YTlmNDc0NmFlZTNhMzA1NDlmZWY3MmNjZjY5Y2NjNjBiNWIzNjUyNWRlYjNhYjQjOHlCS2w1dmdQcVlKVlN0aEVJdVktdUNUV2JoTnMzcmR4bFBQeFhZQW9pbyJ9.eyJjbGllbnRfaWQiOiJkaWQ6aW90YTpybXM6MHgyOWE2NmFhNDI5MDJkM2JhOGE5ZjQ3NDZhZWUzYTMwNTQ5ZmVmNzJjY2Y2OWNjYzYwYjViMzY1MjVkZWIzYWI0IiwicmVkaXJlY3RfdXJpIjoiaHR0cDovL2luc3VyYW5jZS5zZWx2LmxvY2FsOjgxL3JlZGlyZWN0Iiwic3RhdGUiOiJhYmM2Y2YxYy1kYzgzLTRjNjAtYTA3MC0yZGVlYTkxN2MzZWMiLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4iLCJzY29wZSI6Im9wZW5pZCIsInJlc3BvbnNlX21vZGUiOiJkaXJlY3RfcG9zdCIsIm5vbmNlIjoidGVzdCIsImNsaWVudF9tZXRhZGF0YSI6eyJzdWJqZWN0X3N5bnRheF90eXBlc19zdXBwb3J0ZWQiOlsiZGlkOmlvdGE6cm1zIl19fQ.21VgOxEATtpuQMaEB8Ct2k-oy3LcKCq7FhrjgaIfiQywETJaF_zc1BneRbYhyC4dTkfiYORBOwYrNLWYvDG3Bw