proto < ../../../proto/user/user.proto

@host=http://selv.local:5001/backend
###
{{
    //pre request script
    exports.data = new TextEncoder().encode("test");
}}

GRPC /UsersService/ConnectUser
{
    "did": "test",
    "code": "063bf112-5e45-4529-a085-fd91c79d8837"
}
###
{{
    //pre request script
    exports.data = new TextEncoder().encode("test");
}}

GRPC /UsersService/PresentCredential
{
    "user": {
        "did": "test",
        "code": "063bf112-5e45-4529-a085-fd91c79d8837"
    },
    "vp": {}
}
###
{{
    //pre request script
    exports.data = new TextEncoder().encode("test");
}}

GRPC /UsersService/RequestCredential
{
    "user": {
        "did": "test",
        "code": "063bf112-5e45-4529-a085-fd91c79d8837"
    },
    "unsignedCredentials": [
        {}
    ]
}