@host=http://bank.selv.local:81
###
GET /api/health
###
GET /api/token
###
GET /.well-known/oauth-authorization-server
###
GET /.well-known/openid-credential-issuer
###
POST /api/credential
###
GET /api/credential-offer/05c438e5-f27a-4572-b57b-8b2be990b6ba
###
GET /api/offer/05c438e5-f27a-4572-b57b-8b2be990b6ba
###
{{
const crypto = require('crypto');

const holder_did = "did:key:z6MkquY2TrE7KeuBNRAJ4eZbPqtYeCyGXe8seQNfK1ZXAumj";
const state = "775dd08e-c0cd-417b-9a0e-f65f8bd33fea";
const nonce = "QtIxNkPd_NX_hBqIeTR7-";

const header =   {
  "kid": "did:key:z6MkquY2TrE7KeuBNRAJ4eZbPqtYeCyGXe8seQNfK1ZXAumj#z6MkquY2TrE7KeuBNRAJ4eZbPqtYeCyGXe8seQNfK1ZXAumj",
  "alg": "EdDSA",
  "typ": "JWT"
}
const encodedHeaders = Buffer.from(JSON.stringify(header), "utf8").toString("base64url");

const claims = {
  "iat": 1714457784,
  "request_uri": `${host}/api/offers/siop/N5NGrHKYYxMMIC3uZ9BLn`, //TODO: what is that?
  "response_type": "id_token",
  state,
  "client_metadata": {
    "subject_syntax_types_supported": [
      "did:key"
    ],
    "id_token_signing_alg_values_supported": [
      "EdDSA"
    ],
    "client_name": "TEST",
    "logo_uri": "TBD"
  },
  "redirect_uri": `${host}/api/auth`,
  "resolver": {
    "registry": {}
  },
  "scope": "openid",
  "response_mode": "post",
  "client_id": holder_did,
  nonce,
  "iss": holder_did
}
const encodedPayload = Buffer.from(JSON.stringify(claims), "utf8").toString("base64url");

const encodedSignature = crypto.createHmac('sha256', "mysecret").update(`${encodedHeaders}.${encodedPayload}`).digest("base64url")

console.log(encodedSignature);
const jwt = `${encodedHeaders}.${encodedPayload}.${encodedSignature}`;
console.log(jwt);
exports.jwt = jwt
}}

POST /api/auth
Content-Type: application/x-www-form-urlencoded

id_token={{jwt}}