@host=http://bank.selv.local:81
###
GET /api/health
###
POST /api/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:pre-authorized_code
&pre-authorized_code=eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDppb3RhOnJtczoweGZjNDNjZjRlOTA3MTdlMzdjYmI3ZWZjZjYyYmIxYjEyY2RlMGY3YmY3YTk1NTJjMjY2NjQyYzllMDIwMzBiZGEjZGVUODVNU2x2MXZReDlHYjZtWnNtNmRxQ1J0WjVNTUFtQWRrNEM5LXM2NCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU5ODMwNjAsImV4cCI6MTcxNjA2OTQ2MCwiaWQiOiJQZ0dCcW9Ib01nU1c0S2R3ckRyVXUiLCJzdGF0ZSI6IjEwMjljMWFhLTU0ZWUtNDFlYS1hYTZhLTgyZTdlZmMxMGRiZiIsImlzcyI6ImRpZDppb3RhOnJtczoweGZjNDNjZjRlOTA3MTdlMzdjYmI3ZWZjZjYyYmIxYjEyY2RlMGY3YmY3YTk1NTJjMjY2NjQyYzllMDIwMzBiZGEifQ.A9oFzNLWJYIXBFLlu7jGzeBoSHSeJj3hVeYhVi0XYqdRQnNm2zpFMpLeqxbczD4n_qUuz4L2kC64Bmk6gCZlDw
###
GET /.well-known/oauth-authorization-server
###
GET /.well-known/openid-credential-issuer
###
POST /api/credential
###
GET /api/credential-offer/372e0ad6-e601-473d-b632-bcf1762e79aa
###
GET /api/offer/c10dc98c-06e4-4199-bc2d-3d6cff1a2e25
###
{{

const utils = require('../../scripting/dist/bundle5.js');

const jwt = async () => {

  const { didDocument, keyPairs } = await utils.getDIDKey();
  const { id:did, authentication } = didDocument; 

  const issuer_did = "test"

  const header = {
    kid: `${authentication}`,
    alg: "EdDSA",
    typ: "JWT"
  }

  const encodedHeaders = Buffer.from(JSON.stringify(header), "utf8").toString("base64url");

  const claims = {
  "iat": 1714775844,
  "request_uri": "http%3A%2F%2Fbank.selv.local%3A81%2Fapi%2Foffer%2F9f38f7c9-708b-4351-99b4-12cc75f9c94c",
  "response_type": "id_token",
  "state": "test",
  "nonce": "3X8JDguMcK76sYRZifbRJ",
  "client_metadata": {
    "subject_syntax_types_supported": [
      "did:key"
    ],
    "id_token_signing_alg_values_supported": [
      "EdDSA"
    ]
  },
  "redirect_uri": "http://bank.selv.local:81/api/auth",
  "resolver": {
    "registry": {}
  },
  "scope": "openid",
  "response_mode": "post",
  "client_id": "did:iota:rms:0xc276250e9292c35bc1692cf81f417bbec3a1c825d5e47a9082d656a08a039b05",
  "iss": "did:iota:rms:0xc276250e9292c35bc1692cf81f417bbec3a1c825d5e47a9082d656a08a039b05"
}
  const encodedPayload = Buffer.from(JSON.stringify(claims), "utf8").toString("base64url");

  const encodedSignature = await utils.sign(`${encodedHeaders}.${encodedPayload}`)

  const jwt = `${encodedHeaders}.${encodedPayload}.${encodedSignature}`;
  return jwt;
}
exports.jwt = jwt();
}}

POST /api/auth
Content-Type: application/x-www-form-urlencoded

id_token={{jwt}}