proto < ../../../proto/oid4vc/siopv2.proto
proto < ../../../proto/oid4vc/oid4vp.proto
proto < ../../../proto/oid4vc/oid4vci.proto

@host=http://selv.local:5001/oid4vc-tanglelabs
###
GRPC /SIOPV2/CreateRequest
{
    "state": "test"
}
###
GRPC /OID4VP/CreateRequest
{
    "state": "test",
    "presentationDefinition": {
        "test": "test"
    }
}
###
GRPC /OID4VCI/CreateOffer
{
 "credentials": ["wa_driving_license"]
}