import { 
  Landing,
  IntroShowTodos,
  IntroShowMobile,
  AppDownloadQR,
  ProveIdentity,
  SingInConfirmation,
  CompanyData,
  CompanyDetails,
  Confirmation,
  BankData,
  InsuranceData,
  IncorporatedCompanies,
  GreatSuccess,
} from './pages'

export const routes = [ 
  { path: '/', page: Landing },
  { path: '/progress/demo/todos/2', page: IntroShowTodos }, 
  { path: '/progress/demo/app/2', page: IntroShowMobile }, 
  { path: '/progress/company/list/2', page: IncorporatedCompanies }, 
  { path: '/progress/company/app/2', page: AppDownloadQR }, 
  { path: '/progress/company/prove/2', page: ProveIdentity }, 
  { path: '/progress/company/signin/2', page: SingInConfirmation }, 
  { path: '/progress/company/data/2', page: CompanyData }, 
  { path: '/progress/company/success/2', page: Confirmation }, 
  { path: '/progress/company/details/3/:companyId', page: CompanyDetails }, 
  { path: '/progress/bank/prove/3', page: ProveIdentity }, 
  { path: '/progress/bank/data/3', page: BankData },
  { path: '/progress/bank/success/4', page: Confirmation }, 
  { path: '/progress/company/details/4/:companyId', page: CompanyDetails }, 
  { path: '/progress/insurance/prove/4', page: ProveIdentity }, 
  { path: '/progress/insurance/data/4', page: InsuranceData },
  { path: '/progress/insurance/success/4', page: Confirmation }, 
  { path: '/progress/company/details/5/:companyId', page: CompanyDetails },
  { path: '/progress/demo/success/5', page: GreatSuccess },  
]

export const mainSteps = [
  { title: 'Yoga class' },
  { title: 'Eat breakfast' },
  { title: 'Set up a company' },
  { title: 'Get a bank account' },
  { title: 'Get liability insurance' },
  { title: 'Treat yourself' },
]